package proyecto2.cariaco.ceballos;

import java.util.concurrent.Semaphore;

/**
 *
 * @author Bryan
 */
public class Interfaz extends javax.swing.JFrame {

    private Semaphore s;
    private SistemaOperativo sistema;
    private Procesador procesador;
    //private Proceso capcom;
    //private Proceso nintendo;
    private Cola ganadores;
    private int ultimo_resultado;
    private int tiempoProcesador;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(1300, 800);
        this.ganadores = new Cola();
        this.ultimo_resultado = 0;
        this.procesador = null;
        this.sistema = null;
        this.tiempoProcesador = 10;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comenzarJuego = new javax.swing.JButton();
        inputPersonajesIniciales = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cola1Capcom = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cola2Capcom = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cola3Capcom = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        refuerzoCapcom = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cola1Nintendo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cola2Nintendo = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cola3Nintendo = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        refuerzoNintendo = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        colaGanadores = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ganadoresNintendo = new javax.swing.JLabel();
        ganadoresCapcom = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        estadoProcesador = new javax.swing.JLabel();
        modificarTiempo = new javax.swing.JButton();
        inputTiempoProcesador = new javax.swing.JTextField();
        etiquetaPersonajesIniciales = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        peleadorNintendo = new javax.swing.JLabel();
        peleadorCapcom = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comenzarJuego.setText("Comenzar Juego");
        comenzarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(comenzarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        inputPersonajesIniciales.setText("10");
        inputPersonajesIniciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPersonajesInicialesActionPerformed(evt);
            }
        });
        getContentPane().add(inputPersonajesIniciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 150, 30));

        jLabel1.setText("Duración de cada combate (segundos):");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabel2.setText("Cola 1:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, -1, -1));

        cola1Capcom.setText("Vacía");
        getContentPane().add(cola1Capcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, -1, -1));

        jLabel4.setText("Cola 2:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, -1, -1));

        cola2Capcom.setText("Vacía");
        getContentPane().add(cola2Capcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, -1, -1));

        jLabel6.setText("Cola 3:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 370, -1, -1));

        cola3Capcom.setText("Vacía");
        getContentPane().add(cola3Capcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, -1, -1));

        jLabel8.setText("Cola de refuerzo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 460, -1, -1));

        refuerzoCapcom.setText("Vacía");
        getContentPane().add(refuerzoCapcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, -1, -1));

        jLabel10.setText("Capcom");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, -1, -1));

        jLabel11.setText("Cola 1:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        cola1Nintendo.setText("Vacía");
        getContentPane().add(cola1Nintendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jLabel13.setText("Cola 2:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        cola2Nintendo.setText("Vacía");
        getContentPane().add(cola2Nintendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jLabel15.setText("Cola 3:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        cola3Nintendo.setText("Vacía");
        getContentPane().add(cola3Nintendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jLabel17.setText("Cola de refuerzo:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        refuerzoNintendo.setText("Vacía");
        getContentPane().add(refuerzoNintendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        jLabel19.setText("Nintendo");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel20.setText("Ganadores");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 620, -1, -1));

        colaGanadores.setText("Vacía");
        getContentPane().add(colaGanadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 660, -1, -1));

        jLabel22.setText("Ganadores:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, -1, -1));

        jLabel23.setText("Ganadores:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, -1, -1));

        ganadoresNintendo.setText("0");
        getContentPane().add(ganadoresNintendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 30, 20));

        ganadoresCapcom.setText("0");
        getContentPane().add(ganadoresCapcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 570, 30, 30));

        jLabel26.setText("Estado procesador:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, -1));

        estadoProcesador.setText("Esperando");
        getContentPane().add(estadoProcesador, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 80, 20));

        modificarTiempo.setText("Modificar tiempo");
        modificarTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarTiempoActionPerformed(evt);
            }
        });
        getContentPane().add(modificarTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, -1));

        inputTiempoProcesador.setText("10");
        inputTiempoProcesador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTiempoProcesadorActionPerformed(evt);
            }
        });
        getContentPane().add(inputTiempoProcesador, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 150, 30));

        etiquetaPersonajesIniciales.setText("Número de personajes iniciales:");
        getContentPane().add(etiquetaPersonajesIniciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        jLabel5.setText("Peleador Nintendo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jLabel7.setText("Peleador Capcom:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, -1, -1));

        peleadorNintendo.setText("Ninguno");
        getContentPane().add(peleadorNintendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        peleadorCapcom.setText("Ninguno");
        getContentPane().add(peleadorCapcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, -1, -1));

        jLabel9.setText("Resultado:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        resultado.setText("Esperando resultado");
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comenzarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarJuegoActionPerformed
        // TODO add your handling code here:
        try {
            if (Integer.parseInt(inputPersonajesIniciales.getText()) > 0 && Integer.parseInt(inputTiempoProcesador.getText()) > 0) {
                s = new Semaphore(1, true);
                
                comenzarJuego.setVisible(false);
                inputPersonajesIniciales.setVisible(false);
                etiquetaPersonajesIniciales.setVisible(false);
                
                procesador = new Procesador(s, getTiempoProcesador(), this);
                sistema = new SistemaOperativo(s, Integer.parseInt(inputPersonajesIniciales.getText()), this);

                procesador.start();
                sistema.start();
            } else {

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_comenzarJuegoActionPerformed

    private void inputPersonajesInicialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPersonajesInicialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPersonajesInicialesActionPerformed

    private void inputTiempoProcesadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTiempoProcesadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTiempoProcesadorActionPerformed

    private void modificarTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarTiempoActionPerformed
        // TODO add your handling code here:
        try {
            if (Integer.parseInt(inputTiempoProcesador.getText()) > 0) {
                if (procesador != null) {
                    setTiempoProcesador(Integer.parseInt(inputTiempoProcesador.getText()));
                    procesador.setTiempo(getTiempoProcesador());
                } else {
                    setTiempoProcesador(Integer.parseInt(inputTiempoProcesador.getText()));
                }
            } else {

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_modificarTiempoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel cola1Capcom;
    public javax.swing.JLabel cola1Nintendo;
    public javax.swing.JLabel cola2Capcom;
    public javax.swing.JLabel cola2Nintendo;
    public javax.swing.JLabel cola3Capcom;
    public javax.swing.JLabel cola3Nintendo;
    public javax.swing.JLabel colaGanadores;
    private javax.swing.JButton comenzarJuego;
    public javax.swing.JLabel estadoProcesador;
    private javax.swing.JLabel etiquetaPersonajesIniciales;
    public javax.swing.JLabel ganadoresCapcom;
    public javax.swing.JLabel ganadoresNintendo;
    private javax.swing.JTextField inputPersonajesIniciales;
    private javax.swing.JTextField inputTiempoProcesador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton modificarTiempo;
    public javax.swing.JLabel peleadorCapcom;
    public javax.swing.JLabel peleadorNintendo;
    public javax.swing.JLabel refuerzoCapcom;
    public javax.swing.JLabel refuerzoNintendo;
    public javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the sistema
     */
    public SistemaOperativo getSistema() {
        return sistema;
    }

    /**
     * @param sistema the sistema to set
     */
    public void setSistema(SistemaOperativo sistema) {
        this.sistema = sistema;
    }

    /**
     * @return the procesador
     */
    public Procesador getProcesador() {
        return procesador;
    }

    /**
     * @param procesador the procesador to set
     */
    public void setProcesador(Procesador procesador) {
        this.procesador = procesador;
    }

    /**
     * @return the ultimo_resultado
     */
    public int getUltimo_resultado() {
        return ultimo_resultado;
    }

    /**
     * @param ultimo_resultado the ultimo_resultado to set
     */
    public void setUltimo_resultado(int ultimo_resultado) {
        this.ultimo_resultado = ultimo_resultado;
    }

    /**
     * @return the ganadores
     */
    public Cola getGanadores() {
        return ganadores;
    }

    /**
     * @param ganadores the ganadores to set
     */
    public void setGanadores(Cola ganadores) {
        this.ganadores = ganadores;
    }

    /**
     * @return the tiempoProcesador
     */
    public int getTiempoProcesador() {
        return tiempoProcesador;
    }

    /**
     * @param tiempoProcesador the tiempoProcesador to set
     */
    public void setTiempoProcesador(int tiempoProcesador) {
        this.tiempoProcesador = tiempoProcesador;
    }
}
